define

  conhecimento sub relation,
    relates relativo,
    relates origina;

  assunto sub entity,
    plays relativo,
    has pessoaFJ,
    has grupo,
    has familia,
    has tipo,
    has objeto;

  base sub entity,
    plays origina,
    has servico,
    has pergunta,
    has resposta;
    

  servico sub attribute,
	  datatype string;
  grupo sub attribute,
	  datatype string;
  família sub attribute,
	  datatype string;
  tipo sub attribute,
	  datatype string;
  objeto sub attribute,
	  datatype string;
  pessoaFJ sub attribute,
	  datatype string;
  pergunta sub attribute,
	  datatype string;
  resposta sub attribute,
	  datatype string;
